blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion / question
    url: https://github.com/raman325/vizio-smartcast/discussions
    about: For open-ended questions, design discussions, or help requests.
